version: '2'
services:
    wedoc-app:
        image: wedoc
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://wedoc-mysql:3306/wedoc?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    wedoc-mysql:
        extends:
            file: mysql.yml
            service: wedoc-mysql
